### ISSUE TITLE
RNPxl sometimes crashes when clicking on "Show spectrum"

### ISSUE THREAD

**Issue by hannesveit** [OpenMS/PDCommunityNodes#1]
Issue is intermittent.

`System.NullReferenceException: Object reference not set to an instance of an object. at Thermo.Discoverer.EntityDataFramework.Controls.GenericGridControl.CustomValueEditors.ShowSpectrumButtonValueEditor.OnButtonPressed(Object cellContents) at Thermo.Discoverer.EntityDataFramework.Controls.GenericGridControl.CustomValueEditors.ShowSpectrumButtonValueEditor.PART_LinkButton_OnClick(Object sender, RoutedEventArgs e)[….]`

**Comment by hannesveit** [comment]
Haven't really been able to reproduce this yet. We received two similar bug reports like this (without log file, data, or any other further information). My best guess is that the "Spectra to store" parameter in the "MSF Files" node of the consensus workflow was not set to "All", but to something else. Then depending on the Processing Workflow all or only some of the spectra are not transferred to the consensus step and hence the crash when trying to access these spectra.

This was the only way in which I could reproduce the reported error message.

Solution (?): add exception handling, display message box hinting at this potential issue when exception is thrown on button press.

**Comment by hannesveit** [comment]
Finally been able to reproduce the bug even with "Spectra to store" set to "All": When several analyses results are open at the same time and switching back and forth between them, clicking on "Show Spectrum" does only work for the most recently produced result. We're probably referring to the wrong workflow ID?

**Comment by hannesveit** [comment]
The main issue turned out to be a bug in the provided sample implementation for adding these "Show Spectrum" buttons. It did not support multiple result tabs containing these buttons to be open at the same time. Fixed in feaa2fc.

**Comment by timosachsenberg** [comment]
😃 cool
